- hosts: all
  sudo: True

  vars:
    worker_processes: auto
    worker_connections: 10240

  tasks:

    - include: 'tasks/main.yml'

    - name: copy Nginx configuration
      template: src=templates/nginx.conf.j2  dest=/etc/nginx/nginx.conf
      notify:
        - restart nginx

  handlers:
    - include: 'handlers/main.yml'

